image: node:8.14.0-alpine

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    - yarn.lock

stages:
  - eslint_check
  - stylelint_check
  - flow_check
  - jest_check

before_script:
  - apk --no-cache --virtual build-dependencies add \
    python2=2.7.15-r2 \
    make=4.2.1-r2 \
    g++=6.4.0-r9
  - yarn install --ignore-engines
  - apk del build-dependencies

eslint_check:
  stage: eslint_check
  script:
    - yarn test:eslint
  only:
    - branches

stylelint_check:
  stage: stylelint_check
  script:
    - yarn test:stylelint
  only:
    - branches

flow_check:
  stage: flow_check
  script:
    - yarn test:flow
  only:
    - branches

jest_check:
  stage: jest_check
  script:
    - yarn test:jest
  only:
    - branches
